---
title: "Are limited editions an investing worth?"
author: "Jens Laufer"
date: "3 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("R/data.R")
source("R/vis.R")
```
```{r}

```


## From the top most common classes in the data set, which has the highest price increase?


```{r}
interesting_classes <- data %>% 
  mutate(price_increase_pct=100*(highest_price-lowest_price)/lowest_price) %>% 
  filter(is.nan(price_increase_pct)|is.finite(price_increase_pct)) %>% 
  group_by(class) %>% 
  summarise(n=n()) %>% 
  arrange(-n) %>% 
  filter(n>1000) %>% 
  pull(class)
interesting_classes
```
```{r}
dataWithPriceIncrease <- data %>% 
  mutate(price_increase_pct=100*(highest_price-lowest_price)/lowest_price) %>%
  filter(!is.na(price_increase_pct)&is.finite(price_increase_pct)) 
```
```{r}
.class <- "Art Print"
.var <- "lowest_price"

bucketData <- dataWithPriceIncrease %>% 
  filter(class==.class) %>% 
  mutate(bucket=cut(!!sym(.var), dataWithPriceIncrease %>% filter(class==.class) %>% pull(!!sym(.var)) %>% quantile(), include.lowest=T)) 


bucketData %>% 
  ggplot(aes(x = bucket, y = price_increase_pct)) +
  geom_boxplot() +
  scale_y_continuous(labels = comma) +
  scale_x_discrete(limit=bucketData %>%  group_by(bucket) %>% summarise(median=median(price_increase_pct, na.rm = T)) %>% arrange(-median) %>% pull(bucket)) +
  coord_cartesian(ylim = c(0,700))
```



```{r}

dataWithPriceIncrease %>%
  filter(average_price > 500, average_price<2000) %>% 
  filter(class %in% interesting_classes) %>% 
  filter(price_increase_pct>0) %>% 
  ggplot(aes(x = class, y=price_increase_pct)) +
  scale_y_continuous(labels = comma) +
  geom_boxplot() +
  scale_x_discrete(guide = guide_axis(angle = 45), limit=dataWithPriceIncrease %>% filter(class %in% interesting_classes) %>% group_by() %>% summarise(median=median(price_increase_pct, na.rm = T)) %>% arrange(-median) %>% pull(class)) + 
  coord_cartesian(ylim = c(0,800))
```
```{r}

data %>% 
  mutate(price_increase_pct=100*(highest_price-lowest_price)/lowest_price) %>%
  filter(!is.na(price_increase_pct)&is.finite(price_increase_pct)) %>%  filter(average_price > 500, average_price<2000) %>% 
  group_by(class) %>% 
  summarise(n=n()) %>% 
  arrange(-n)
```


```{r}
data %>% 
  mutate(price_increase_pct=100*(highest_price-lowest_price)/lowest_price) %>% 
  filter(class=="Cinema") %>% 
  arrange(-average_price) %>% 
  select(id,artwork, average_price )
```


```{r}
 data %>% 
  mutate(price_increase_pct=100*(highest_price-lowest_price)/lowest_price) %>%
  filter(!is.na(price_increase_pct)&is.finite(price_increase_pct)) %>% 
  filter(average_price < 2000, average_price > 500)
```



```{r}
dataWithPriceIncrease %>%
  ggplot(aes(x = technique, y = price_increase_pct)) +
  geom_boxplot() +
  scale_y_continuous(trans = "log10") +
  scale_x_discrete(,
                   limit = (
                     dataWithPriceIncrease %>% group_by(technique) %>% summarise(median =
                                                                                   median(price_increase_pct, na.rm = T)) %>% arrange(-median) %>% pull(technique)
                   )) +
  coord_flip()
```

```{r fig.height=20, fig.width=20}
classTechniques <- dataWithPriceIncrease %>% 
  group_by(class, technique) %>% 
  summarise(n=n(), .groups = "drop_last") %>% 
  filter(!is.na(class) & !is.na(technique)) %>% 
  arrange(-n)
p1 <-  classTechniques %>% 
  ggplot(aes(x = class, y = technique, size=n)) +
  geom_point() +
  scale_x_discrete(guide = guide_axis(angle = 45))
p1
classTechniques
```  


