---
title: "Is it realistic to get high potential prints in a price range of 500-2500?"
author: "Jens Laufer"
date: "5 3 2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F)
```

```{r}
source("R/data.R")
source("R/vis.R")
```

```{r}
library(emojifont)
```




```{r}
totalArtPieces <- data %>% nrow()
numArtClasses <- data %>% distinct(class) %>% nrow()
numArtists <- data %>% distinct(artist_id) %>% nrow()
totalArtPiecesWithPricing <- data %>% 
  drop_na(original_price, average_price, lowest_price, highest_price) %>% 
  nrow() 

totalNumPrintArts <- data %>% filter(class == "Art Print") %>% nrow() 
totalNumPrintArtsWithPricing <- data %>% filter(class == "Art Print") %>% drop_na(original_price, average_price, lowest_price, highest_price) %>% nrow() 
```



```{r}
rep(seq(2, 20, width))
```


```{r}
width <- 6
values <- c(
  paste0("+", round(totalArtPieces / 1000, 0), "k"),
  paste0("+", round(totalArtPiecesWithPricing / 1000, 0), "k"),
  numArtClasses,
  paste0("+", round(numArtists / 1000, 0), "k")
)
labels <- c("Art Pieces",
            "Priced Art Pieces",
            "Art Classes",
            "Artists")
num <- values %>% length()

facts <- data.frame(
  x = rep(seq(2, num * width, width)),
  y = rep(width, num),
  h = rep(6, num),
  w = rep(width, num),
  value = values,
  info = labels,
  shape = rep(fontawesome(search_fontawesome("chart")[1]), num),
  font_family = rep("fontawesome-webfont", num),
  color = seq(1, num, 1) %>% as.factor()
)

facts %>%
  ggplot(aes(x,
             y,
             height = h,
             width = w)) +
  geom_tile(aes(fill = color)) +
  geom_text(
    color = "white",
    fontface = "bold",
    size = 11,
    aes(label = value, x = x - 2.5, y = y + 1),
    hjust = 0
  ) +
  geom_text(
    color = "white",
    fontface = "bold",
    size = 4.5,
    aes(label = info, x = x - 2.5, y = y - 1),
    hjust = 0
  ) +
  geom_text(
    size = 18,
    aes(
      label = shape,
      family = font_family,
      x = x + 1,
      y = y + 1
    ),
    alpha = 0.25
  ) +
  scale_fill_brewer(type = "qual", palette = "Dark2") +
  coord_fixed() +
  theme_void() +
  guides(fill = FALSE)
```



## Is it realistic to get high potential Print Art pieces in the range of $500-$2500?



```{r}
totalNumPrintArts %>% 
  valueBox(totalNumPrintArts, "tachometer", "#ff9999")
```

I first filter all `r totalNumPrintArts` `r totalNumPrintArtsWithPricing`



```{r}
priceBucketData <- printArtData %>%
  mutate(original_price_bucket = cut(original_price, c(
    min(original_price), 500, 2500, 5000, max(original_price) + 1
  )),
  include.lowest = T) %>%
  drop_na(original_price_bucket)

priceBucketData %>%
  ggplot(aes(x = original_price_bucket, y = priceIncreasePercentage)) +
  geom_jitter(color = "#ffbb00", alpha = .3) +
  geom_boxplot(alpha = 0.6) +
  scale_x_discrete(
    limit = priceBucketData %>% group_by(original_price_bucket) %>% summarise(median = median(priceIncreasePercentage, na.rm = T)) %>%  arrange(-median) %>% pull(original_price_bucket)
  ) +
  coord_cartesian(ylim = c(0, 1000))
```


```{r}
priceBucketData %>% 
  group_by(original_price_bucket) %>% 
  summarize(n=n())
```

```{r}
priceBucketData %>% 
  filter(original_price_bucket=="(500,2.5e+03]")
```


```{r}
priceBucketData <- printArtData %>%
  mutate(
    original_price_bucket = cut(
      original_price,
      printArtData %>% pull(original_price) %>% quantile()
    ),
    include.lowest = T
  ) %>%
  drop_na(original_price_bucket)

priceBucketData %>%
  ggplot(aes(x = original_price_bucket, y = priceIncreasePercentage)) +
  geom_jitter(color = "#ffbb00", alpha = .3) +
  geom_boxplot(alpha = 0.6) +
  scale_x_discrete(
   limit = priceBucketData %>% group_by(original_price_bucket) %>% summarise(median = median(priceIncreasePercentage, na.rm = T)) %>%  arrange(-median) %>% pull(original_price_bucket)
  ) +
  coord_cartesian(ylim = c(0, 1000))
```